# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason Hee
email: hello@jasonhee.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Jason Hee, a Singaporean Web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasonhee.com" # the base hostname & protocol for your site
github_username:  jasonheecs
codepen_username:  jasonheecs
version: 1.1

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "_scss", "gulp", "_js", "src"]

# portfolio collection
collections:
  portfolio:
    output: true
    permalink: /:title/

# defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      categories: "Portfolio"
      layout: "portfolio"
      images: 
        base_url: "/images/works/"

gems:
  - jekyll-sitemap
theme: jekyll-theme-minimal